spring.application.name=backendAngkorLiving
spring.datasource.url=jdbc:postgresql://localhost:5432/DatabaseAngkorlivings
spring.datasource.username=postgres
spring.datasource.password=mora123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=9090
# JWT secret key (must be >= 32 characters for HS256)
jwt.secret=mySuperSecretKeyForJwt1234567890ABCDEF
# Cloudinary
cloudinary.cloud_name=dgmhpq8tt
cloudinary.api_key=121878724238336
cloudinary.api_secret=7LW5OJo8mB_1mFOB9Odh2n8F5D4

BAKONG_ACCOUNT_USERNAME=somora_march@bkrt
BAKONG_ACCOUNT_NAME=MoraComputer
BAKONG_LOCATION=PhnomPenh
NBC_API_URL=https://api-bakong.nbc.gov.kh/

BAKONG_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...



